sudo: false
language: go
go:
  - 1.12.x
  - tip
env:
  - GO111MODULE=on
script:
  - make ci
after_success:
  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash
notifications:
  email: false
